export const Precedence = {
  NONE:       0,
  ASSIGNMENT: 1,
  TERNARY:    2,
  OR:         3,
  AND:        4,
  NOT:        5,
  EQUALITY:   6,
  COMPARISON: 7,
  ADDITION:   8,
  MULTIPLY:   9,
  UNARY:      10,
  POWER:      11,
  CALL:       12,
  INDEX:      13,
};
